# Generated by Django 4.2.6 on 2023-10-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_day', models.DateField()),
                ('subject', models.CharField(max_length=256, verbose_name='Предмет')),
            ],
            options={
                'ordering': ('work_day',),
            },
        ),
    ]
