# Generated by Django 4.2.6 on 2023-10-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='tutor',
            field=models.CharField(default='Иванон Иван Иванович', max_length=256, verbose_name='Преподаватель'),
            preserve_default=False,
        ),
    ]
