# Generated by Django 4.2.6 on 2023-10-25 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ('place',), 'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('group_num',), 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='jsontimetable',
            options={'ordering': ('date_time_of_upload',), 'verbose_name': 'Файл с расписанием', 'verbose_name_plural': 'Файлы с расписанием'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('subject_name',), 'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ('work_day', 'work_start'), 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ('tutor_name',), 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'ordering': ('work_type',), 'verbose_name': 'Тип занятия', 'verbose_name_plural': 'Типы занятий'},
        ),
        migrations.AddField(
            model_name='jsontimetable',
            name='message',
            field=models.CharField(default='hello', max_length=1024, verbose_name='Сообщение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='place',
            field=models.CharField(max_length=20, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_num',
            field=models.CharField(max_length=50, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.IntegerField(default=0, verbose_name='Количество студентов'),
        ),
        migrations.AlterField(
            model_name='jsontimetable',
            name='date_time_of_upload',
            field=models.DateTimeField(auto_now=True, verbose_name='Время загрузки'),
        ),
        migrations.AlterField(
            model_name='jsontimetable',
            name='json_file',
            field=models.FileField(upload_to='uploads/', verbose_name='Название файла'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=100, verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='tutor',
            field=models.ManyToManyField(to='timetable.tutor', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.classroom', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.tutor', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='work_day',
            field=models.DateField(verbose_name='День занятия'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='work_end',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='work_start',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.worktype', verbose_name='Тип занятия'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_name',
            field=models.CharField(max_length=150, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='work_type',
            field=models.CharField(max_length=150, verbose_name='Тип занятия'),
        ),
    ]
