# Generated by Django 4.2.6 on 2023-10-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_jsontimetable_is_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsontimetable',
            name='is_upload',
            field=models.BooleanField(blank=True, default=True, verbose_name='Данные загружены'),
            preserve_default=False,
        ),
    ]
